# SPDX-License-Identifier: GPL-3.0-or-later
# This project is licensed under the Anti-996 License.

# define find-object-files-callable
# 	object_files += parser/parser.o
# endef

# find-object-files :
# 	$(call find-object-files-callable)
# PHONY += find-object-files

out_sub_dirs += parser/

object_files += parser/parser.o
